# Generated by Django 2.2.4 on 2019-08-09 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppUserboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='like_users', to='AppUserboard.Board'),
        ),
    ]
