# Generated by Django 2.2.4 on 2019-08-09 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppUserboard', '0002_board_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='likes',
        ),
    ]
